DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS (
                       id     INTEGER GENERATED BY DEFAULT AS idENTITY PRIMARY KEY,
                       name   VARCHAR(30),
                       tenant VARCHAR(30));

INSERT INTO users VALUES (1, 'patric', 'tenantA');
INSERT INTO users VALUES (2, 'plankton', 'tenantB');
INSERT INTO users VALUES (3, 'bob', 'tenantA');

DROP TABLE IF EXISTS countries;
CREATE TABLE countries (
                           id INTEGER GENERATED BY DEFAULT AS idENTITY PRIMARY KEY,
                           iso VARCHAR(2) NOT NULL,
                           iso3 VARCHAR(3) NOT NULL,
                           iso_numeric INT NOT NULL,
                           country_name VARCHAR(64) NOT NULL,
                           capital VARCHAR(64) NOT NULL,
                           continent_code VARCHAR(2) NOT NULL,
                           currency_code VARCHAR(3) NOT NULL
);

INSERT INTO countries
(iso, iso3, iso_numeric, country_name, capital, continent_code, currency_code)
VALUES
    ('AU', 'AUS', 36, 'Australia', 'Canberra', 'OC', 'AUD'),
    ('DE', 'DEU', 276, 'Germany', 'Berlin', 'EU', 'EUR'),
    ('IN', 'IND', 356, 'India', 'New Delhi', 'AS', 'INR'),
    ('LA', 'LAO', 418, 'Laos', 'Vientiane', 'AS', 'LAK'),
    ('US', 'USA', 840, 'United States', 'Washington', 'NA', 'USD'),
    ('ZW', 'ZWE', 716, 'Zimbabwe', 'Harare', 'AF', 'ZWL');

DROP TABLE IF EXISTS foos;
CREATE TABLE foos (
                       id    INTEGER GENERATED BY DEFAULT AS idENTITY PRIMARY KEY,
                       bar   VARCHAR(1000));


CREATE TABLE post (
                      id int8 NOT NULL,
                      title varchar(255),
                      created_on date,
                      PRIMARY KEY (id)
);

CREATE TABLE post_comment (
                              id int8 NOT NULL,
                              review varchar(255),
                              created_on date,
                              post_id int8, PRIMARY KEY (id)
);

ALTER TABLE post_comment
    ADD CONSTRAINT POST_COMMENT_POST_ID_FK
        FOREIGN KEY (post_id) REFERENCES post;

create index idx_created_on_2 on post (created_on);
create index idx_created_on on post_comment (created_on);
create index idx_post_id on post_comment (post_id);
create index idx_post_comment_post_id on post_comment (post_id);